# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tabuleiro_design.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(759, 762)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btn_A8 = QPushButton(self.centralwidget)
        self.btn_A8.setObjectName(u"btn_A8")
        self.btn_A8.setGeometry(QRect(30, 50, 71, 81))
        self.btn_B8 = QPushButton(self.centralwidget)
        self.btn_B8.setObjectName(u"btn_B8")
        self.btn_B8.setGeometry(QRect(100, 50, 71, 81))
        self.btn_C8 = QPushButton(self.centralwidget)
        self.btn_C8.setObjectName(u"btn_C8")
        self.btn_C8.setGeometry(QRect(170, 50, 71, 81))
        self.btn_D8 = QPushButton(self.centralwidget)
        self.btn_D8.setObjectName(u"btn_D8")
        self.btn_D8.setGeometry(QRect(240, 50, 71, 81))
        self.btn_E8 = QPushButton(self.centralwidget)
        self.btn_E8.setObjectName(u"btn_E8")
        self.btn_E8.setGeometry(QRect(310, 50, 71, 81))
        self.btn_F8 = QPushButton(self.centralwidget)
        self.btn_F8.setObjectName(u"btn_F8")
        self.btn_F8.setGeometry(QRect(380, 50, 71, 81))
        self.btn_G8 = QPushButton(self.centralwidget)
        self.btn_G8.setObjectName(u"btn_G8")
        self.btn_G8.setGeometry(QRect(450, 50, 71, 81))
        self.btn_H8 = QPushButton(self.centralwidget)
        self.btn_H8.setObjectName(u"btn_H8")
        self.btn_H8.setGeometry(QRect(520, 50, 71, 81))
        self.btn_A7 = QPushButton(self.centralwidget)
        self.btn_A7.setObjectName(u"btn_A7")
        self.btn_A7.setGeometry(QRect(30, 130, 71, 81))
        self.btn_B7 = QPushButton(self.centralwidget)
        self.btn_B7.setObjectName(u"btn_B7")
        self.btn_B7.setGeometry(QRect(100, 130, 71, 81))
        self.btn_C7 = QPushButton(self.centralwidget)
        self.btn_C7.setObjectName(u"btn_C7")
        self.btn_C7.setGeometry(QRect(170, 130, 71, 81))
        self.btn_D7 = QPushButton(self.centralwidget)
        self.btn_D7.setObjectName(u"btn_D7")
        self.btn_D7.setGeometry(QRect(240, 130, 71, 81))
        self.btn_E7 = QPushButton(self.centralwidget)
        self.btn_E7.setObjectName(u"btn_E7")
        self.btn_E7.setGeometry(QRect(310, 130, 71, 81))
        self.btn_F7 = QPushButton(self.centralwidget)
        self.btn_F7.setObjectName(u"btn_F7")
        self.btn_F7.setGeometry(QRect(380, 130, 71, 81))
        self.btn_G7 = QPushButton(self.centralwidget)
        self.btn_G7.setObjectName(u"btn_G7")
        self.btn_G7.setGeometry(QRect(450, 130, 71, 81))
        self.btn_H7 = QPushButton(self.centralwidget)
        self.btn_H7.setObjectName(u"btn_H7")
        self.btn_H7.setGeometry(QRect(520, 130, 71, 81))
        self.btn_A6 = QPushButton(self.centralwidget)
        self.btn_A6.setObjectName(u"btn_A6")
        self.btn_A6.setGeometry(QRect(30, 210, 71, 81))
        self.btn_B6 = QPushButton(self.centralwidget)
        self.btn_B6.setObjectName(u"btn_B6")
        self.btn_B6.setGeometry(QRect(100, 210, 71, 81))
        self.btn_C6 = QPushButton(self.centralwidget)
        self.btn_C6.setObjectName(u"btn_C6")
        self.btn_C6.setGeometry(QRect(170, 210, 71, 81))
        self.btn_D6 = QPushButton(self.centralwidget)
        self.btn_D6.setObjectName(u"btn_D6")
        self.btn_D6.setGeometry(QRect(240, 210, 71, 81))
        self.btn_E6 = QPushButton(self.centralwidget)
        self.btn_E6.setObjectName(u"btn_E6")
        self.btn_E6.setGeometry(QRect(310, 210, 71, 81))
        self.btn_F6 = QPushButton(self.centralwidget)
        self.btn_F6.setObjectName(u"btn_F6")
        self.btn_F6.setGeometry(QRect(380, 210, 71, 81))
        self.btn_G6 = QPushButton(self.centralwidget)
        self.btn_G6.setObjectName(u"btn_G6")
        self.btn_G6.setGeometry(QRect(450, 210, 71, 81))
        self.btn_H6 = QPushButton(self.centralwidget)
        self.btn_H6.setObjectName(u"btn_H6")
        self.btn_H6.setGeometry(QRect(520, 210, 71, 81))
        self.btn_A5 = QPushButton(self.centralwidget)
        self.btn_A5.setObjectName(u"btn_A5")
        self.btn_A5.setGeometry(QRect(30, 290, 71, 81))
        self.btn_B5 = QPushButton(self.centralwidget)
        self.btn_B5.setObjectName(u"btn_B5")
        self.btn_B5.setGeometry(QRect(100, 290, 71, 81))
        self.btn_C5 = QPushButton(self.centralwidget)
        self.btn_C5.setObjectName(u"btn_C5")
        self.btn_C5.setGeometry(QRect(170, 290, 71, 81))
        self.btn_D5 = QPushButton(self.centralwidget)
        self.btn_D5.setObjectName(u"btn_D5")
        self.btn_D5.setGeometry(QRect(240, 290, 71, 81))
        self.btn_E5 = QPushButton(self.centralwidget)
        self.btn_E5.setObjectName(u"btn_E5")
        self.btn_E5.setGeometry(QRect(310, 290, 71, 81))
        self.btn_F5 = QPushButton(self.centralwidget)
        self.btn_F5.setObjectName(u"btn_F5")
        self.btn_F5.setGeometry(QRect(380, 290, 71, 81))
        self.btn_G5 = QPushButton(self.centralwidget)
        self.btn_G5.setObjectName(u"btn_G5")
        self.btn_G5.setGeometry(QRect(450, 290, 71, 81))
        self.btn_H5 = QPushButton(self.centralwidget)
        self.btn_H5.setObjectName(u"btn_H5")
        self.btn_H5.setGeometry(QRect(520, 290, 71, 81))
        self.btn_A4 = QPushButton(self.centralwidget)
        self.btn_A4.setObjectName(u"btn_A4")
        self.btn_A4.setGeometry(QRect(30, 370, 71, 81))
        self.btn_B4 = QPushButton(self.centralwidget)
        self.btn_B4.setObjectName(u"btn_B4")
        self.btn_B4.setGeometry(QRect(100, 370, 71, 81))
        self.btn_C4 = QPushButton(self.centralwidget)
        self.btn_C4.setObjectName(u"btn_C4")
        self.btn_C4.setGeometry(QRect(170, 370, 71, 81))
        self.btn_D4 = QPushButton(self.centralwidget)
        self.btn_D4.setObjectName(u"btn_D4")
        self.btn_D4.setGeometry(QRect(240, 370, 71, 81))
        self.btn_E4 = QPushButton(self.centralwidget)
        self.btn_E4.setObjectName(u"btn_E4")
        self.btn_E4.setGeometry(QRect(310, 370, 71, 81))
        self.btn_F4 = QPushButton(self.centralwidget)
        self.btn_F4.setObjectName(u"btn_F4")
        self.btn_F4.setGeometry(QRect(380, 370, 71, 81))
        self.btn_G4 = QPushButton(self.centralwidget)
        self.btn_G4.setObjectName(u"btn_G4")
        self.btn_G4.setGeometry(QRect(450, 370, 71, 81))
        self.btn_H4 = QPushButton(self.centralwidget)
        self.btn_H4.setObjectName(u"btn_H4")
        self.btn_H4.setGeometry(QRect(520, 370, 71, 81))
        self.btn_A3 = QPushButton(self.centralwidget)
        self.btn_A3.setObjectName(u"btn_A3")
        self.btn_A3.setGeometry(QRect(30, 450, 71, 81))
        self.btn_B3 = QPushButton(self.centralwidget)
        self.btn_B3.setObjectName(u"btn_B3")
        self.btn_B3.setGeometry(QRect(100, 450, 71, 81))
        self.btn_C3 = QPushButton(self.centralwidget)
        self.btn_C3.setObjectName(u"btn_C3")
        self.btn_C3.setGeometry(QRect(170, 450, 71, 81))
        self.btn_D3 = QPushButton(self.centralwidget)
        self.btn_D3.setObjectName(u"btn_D3")
        self.btn_D3.setGeometry(QRect(240, 450, 71, 81))
        self.btn_E3 = QPushButton(self.centralwidget)
        self.btn_E3.setObjectName(u"btn_E3")
        self.btn_E3.setGeometry(QRect(310, 450, 71, 81))
        self.btn_F3 = QPushButton(self.centralwidget)
        self.btn_F3.setObjectName(u"btn_F3")
        self.btn_F3.setGeometry(QRect(380, 450, 71, 81))
        self.btn_G3 = QPushButton(self.centralwidget)
        self.btn_G3.setObjectName(u"btn_G3")
        self.btn_G3.setGeometry(QRect(450, 450, 71, 81))
        self.btn_H3 = QPushButton(self.centralwidget)
        self.btn_H3.setObjectName(u"btn_H3")
        self.btn_H3.setGeometry(QRect(520, 450, 71, 81))
        self.btn_A2 = QPushButton(self.centralwidget)
        self.btn_A2.setObjectName(u"btn_A2")
        self.btn_A2.setGeometry(QRect(30, 530, 71, 81))
        self.btn_B2 = QPushButton(self.centralwidget)
        self.btn_B2.setObjectName(u"btn_B2")
        self.btn_B2.setGeometry(QRect(100, 530, 71, 81))
        self.btn_C2 = QPushButton(self.centralwidget)
        self.btn_C2.setObjectName(u"btn_C2")
        self.btn_C2.setGeometry(QRect(170, 530, 71, 81))
        self.btn_D2 = QPushButton(self.centralwidget)
        self.btn_D2.setObjectName(u"btn_D2")
        self.btn_D2.setGeometry(QRect(240, 530, 71, 81))
        self.btn_E2 = QPushButton(self.centralwidget)
        self.btn_E2.setObjectName(u"btn_E2")
        self.btn_E2.setGeometry(QRect(310, 530, 71, 81))
        self.btn_F2 = QPushButton(self.centralwidget)
        self.btn_F2.setObjectName(u"btn_F2")
        self.btn_F2.setGeometry(QRect(380, 530, 71, 81))
        self.btn_G2 = QPushButton(self.centralwidget)
        self.btn_G2.setObjectName(u"btn_G2")
        self.btn_G2.setGeometry(QRect(450, 530, 71, 81))
        self.btn_H2 = QPushButton(self.centralwidget)
        self.btn_H2.setObjectName(u"btn_H2")
        self.btn_H2.setGeometry(QRect(520, 530, 71, 81))
        self.btn_A1 = QPushButton(self.centralwidget)
        self.btn_A1.setObjectName(u"btn_A1")
        self.btn_A1.setGeometry(QRect(30, 610, 71, 81))
        self.btn_B1 = QPushButton(self.centralwidget)
        self.btn_B1.setObjectName(u"btn_B1")
        self.btn_B1.setGeometry(QRect(100, 610, 71, 81))
        self.btn_C1 = QPushButton(self.centralwidget)
        self.btn_C1.setObjectName(u"btn_C1")
        self.btn_C1.setGeometry(QRect(170, 610, 71, 81))
        self.btn_D1 = QPushButton(self.centralwidget)
        self.btn_D1.setObjectName(u"btn_D1")
        self.btn_D1.setGeometry(QRect(240, 610, 71, 81))
        self.btn_E1 = QPushButton(self.centralwidget)
        self.btn_E1.setObjectName(u"btn_E1")
        self.btn_E1.setGeometry(QRect(310, 610, 71, 81))
        self.btn_F1 = QPushButton(self.centralwidget)
        self.btn_F1.setObjectName(u"btn_F1")
        self.btn_F1.setGeometry(QRect(380, 610, 71, 81))
        self.btn_G1 = QPushButton(self.centralwidget)
        self.btn_G1.setObjectName(u"btn_G1")
        self.btn_G1.setGeometry(QRect(450, 610, 71, 81))
        self.btn_H1 = QPushButton(self.centralwidget)
        self.btn_H1.setObjectName(u"btn_H1")
        self.btn_H1.setGeometry(QRect(520, 610, 71, 81))
        self.label_A = QLineEdit(self.centralwidget)
        self.label_A.setObjectName(u"label_A")
        self.label_A.setGeometry(QRect(30, 690, 71, 25))
        self.label_A.setAlignment(Qt.AlignCenter)
        self.label_B = QLineEdit(self.centralwidget)
        self.label_B.setObjectName(u"label_B")
        self.label_B.setGeometry(QRect(100, 690, 71, 25))
        self.label_B.setAlignment(Qt.AlignCenter)
        self.label_C = QLineEdit(self.centralwidget)
        self.label_C.setObjectName(u"label_C")
        self.label_C.setGeometry(QRect(170, 690, 71, 25))
        self.label_C.setAlignment(Qt.AlignCenter)
        self.label_D = QLineEdit(self.centralwidget)
        self.label_D.setObjectName(u"label_D")
        self.label_D.setGeometry(QRect(240, 690, 71, 25))
        self.label_D.setAlignment(Qt.AlignCenter)
        self.label_E = QLineEdit(self.centralwidget)
        self.label_E.setObjectName(u"label_E")
        self.label_E.setGeometry(QRect(310, 690, 71, 25))
        self.label_E.setAlignment(Qt.AlignCenter)
        self.label_F = QLineEdit(self.centralwidget)
        self.label_F.setObjectName(u"label_F")
        self.label_F.setGeometry(QRect(380, 690, 71, 25))
        self.label_F.setAlignment(Qt.AlignCenter)
        self.label_G = QLineEdit(self.centralwidget)
        self.label_G.setObjectName(u"label_G")
        self.label_G.setGeometry(QRect(450, 690, 71, 25))
        self.label_G.setAlignment(Qt.AlignCenter)
        self.label_H = QLineEdit(self.centralwidget)
        self.label_H.setObjectName(u"label_H")
        self.label_H.setGeometry(QRect(520, 690, 71, 25))
        self.label_H.setAlignment(Qt.AlignCenter)
        self.label_8 = QLineEdit(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 50, 31, 81))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_7 = QLineEdit(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 130, 31, 81))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_6 = QLineEdit(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 210, 31, 81))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_5 = QLineEdit(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 290, 31, 81))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_4 = QLineEdit(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 370, 31, 81))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_3 = QLineEdit(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 450, 31, 81))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_2 = QLineEdit(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 530, 31, 81))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_1 = QLineEdit(self.centralwidget)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(0, 610, 31, 81))
        self.label_1.setAlignment(Qt.AlignCenter)
        self.btn_Confirmar = QPushButton(self.centralwidget)
        self.btn_Confirmar.setObjectName(u"btn_Confirmar")
        self.btn_Confirmar.setGeometry(QRect(630, 50, 91, 81))
        self.btn_Confirmar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(630, 160, 91, 541))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 759, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tabuleiro", None))
        MainWindow.setStyleSheet(QCoreApplication.translate("MainWindow", u"\n"
"QWidget#centralwidget { background-color: #2b2b2b; }\n"
"QPushButton { border: none; }\n"
"/* Casas Claras */\n"
"QPushButton#btn_A8, QPushButton#btn_C8, QPushButton#btn_E8, QPushButton#btn_G8,\n"
"QPushButton#btn_B7, QPushButton#btn_D7, QPushButton#btn_F7, QPushButton#btn_H7,\n"
"QPushButton#btn_A6, QPushButton#btn_C6, QPushButton#btn_E6, QPushButton#btn_G6,\n"
"QPushButton#btn_B5, QPushButton#btn_D5, QPushButton#btn_F5, QPushButton#btn_H5,\n"
"QPushButton#btn_A4, QPushButton#btn_C4, QPushButton#btn_E4, QPushButton#btn_G4,\n"
"QPushButton#btn_B3, QPushButton#btn_D3, QPushButton#btn_F3, QPushButton#btn_H3,\n"
"QPushButton#btn_A2, QPushButton#btn_C2, QPushButton#btn_E2, QPushButton#btn_G2,\n"
"QPushButton#btn_B1, QPushButton#btn_D1, QPushButton#btn_F1, QPushButton#btn_H1 { background-color: #F0D9B5; }\n"
"/* Casas Escuras */\n"
"QPushButton#btn_B8, QPushButton#btn_D8, QPushButton#btn_F8, QPushButton#btn_H8,\n"
"QPushButton#btn_A7, QPushButton#btn_C7, QPushButton#btn_E7, QPushButton#btn_G7,\n"
"QPushButton#"
"btn_B6, QPushButton#btn_D6, QPushButton#btn_F6, QPushButton#btn_H6,\n"
"QPushButton#btn_A5, QPushButton#btn_C5, QPushButton#btn_E5, QPushButton#btn_G5,\n"
"QPushButton#btn_B4, QPushButton#btn_D4, QPushButton#btn_F4, QPushButton#btn_H4,\n"
"QPushButton#btn_A3, QPushButton#btn_C3, QPushButton#btn_E3, QPushButton#btn_G3,\n"
"QPushButton#btn_B2, QPushButton#btn_D2, QPushButton#btn_F2, QPushButton#btn_H2,\n"
"QPushButton#btn_A1, QPushButton#btn_C1, QPushButton#btn_E1, QPushButton#btn_G1 { background-color: #B58863; }\n"
"QPushButton#btn_Confirmar { background-color: #4CAF50; color: white; font-weight: bold; font-size: 14px; border-radius: 4px; }\n"
"QPushButton#btn_Confirmar:hover { background-color: #45a049; }\n"
"QLineEdit { background: transparent; color: #cccccc; border: none; font-size: 14px; font-weight: bold; }\n"
"   ", None))
        self.label_A.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.label_B.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.label_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.label_D.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.label_E.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.label_F.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.label_G.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.label_H.setText(QCoreApplication.translate("MainWindow", u"H", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.btn_Confirmar.setText(QCoreApplication.translate("MainWindow", u"Desistir", None))
        self.graphicsView.setStyleSheet(QCoreApplication.translate("MainWindow", u"background-color: #3b3b3b; border: 1px solid #555555;", None))
    # retranslateUi

